#!/bin/bash
# Rebuild ~/.ssh/authorized_keys from ~/.ssh/authorized_keys.d/ drop-in files.
# This script runs after every chezmoi apply (both primary and work instances).

set -euo pipefail

SSHDIR="$HOME/.ssh"
AUTH_KEYS="$SSHDIR/authorized_keys"
DROP_DIR="$SSHDIR/authorized_keys.d"
LOCAL_FILE="$DROP_DIR/99-local"

# Nothing to do if the drop-in directory doesn't exist yet
if [ ! -d "$DROP_DIR" ]; then
    exit 0
fi

# --- Preserve ssh-copy-id keys into 99-local ---
if [ -f "$AUTH_KEYS" ]; then
    # Collect all keys from managed .d/ files (excluding 99-local itself)
    managed_keys=""
    for f in "$DROP_DIR"/*; do
        [ -f "$f" ] || continue
        [ "$f" = "$LOCAL_FILE" ] && continue
        managed_keys="$managed_keys$(grep -v '^#' "$f" | grep -v '^[[:space:]]*$' || true)
"
    done

    # Find keys in current authorized_keys that aren't in any managed file
    unmanaged=""
    while IFS= read -r line; do
        # Skip blank lines and comments
        case "$line" in
            ""|\#*) continue ;;
        esac
        if ! echo "$managed_keys" | grep -qFx "$line"; then
            unmanaged="$unmanaged$line
"
        fi
    done < "$AUTH_KEYS"

    # Append unmanaged keys to 99-local (create if needed), then deduplicate
    if [ -n "$unmanaged" ]; then
        existing_local=""
        if [ -f "$LOCAL_FILE" ]; then
            existing_local="$(cat "$LOCAL_FILE")"
        fi
        printf '%s\n%s\n' "$existing_local" "$unmanaged" | grep -v '^[[:space:]]*$' | sort -u > "$LOCAL_FILE.tmp"
        mv "$LOCAL_FILE.tmp" "$LOCAL_FILE"
        chmod 600 "$LOCAL_FILE"
    fi
fi

# --- Rebuild authorized_keys from all .d/ files ---
tmpfile="$AUTH_KEYS.tmp.$$"

cat > "$tmpfile" << 'HEADER'
# This file is automatically generated by chezmoi from ~/.ssh/authorized_keys.d/
# DO NOT EDIT THIS FILE DIRECTLY — your changes will be overwritten.
#
# To add keys permanently:
#   - Personal machines: add to authorized_keys.d/10-personal-keys (in dotfiles repo)
#   - Work machines: add to authorized_keys.d/50-work-keys (in dotfiles-work repo)
#   - Local-only keys: add to authorized_keys.d/99-local (survives chezmoi apply)
#
# Keys added via ssh-copy-id are automatically preserved in 99-local.
#
# Caveat: If you remove a key from a managed file, it may reappear in 99-local
# (the rebuild script can't distinguish admin removal from ssh-copy-id addition).
# To fully remove a key, also delete it from 99-local.
HEADER

for f in "$DROP_DIR"/*; do
    [ -f "$f" ] || continue
    printf '\n# --- %s ---\n' "$(basename "$f")"
    cat "$f"
done >> "$tmpfile"

# Ensure file ends with a newline
printf '\n' >> "$tmpfile"

chmod 600 "$tmpfile"
mv "$tmpfile" "$AUTH_KEYS"
